# Generated by Django 5.0.1 on 2025-10-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
