# Generated by Django 5.0.1 on 2025-10-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_verification_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_expiry',
        ),
    ]
