# Generated by Django 5.0.1 on 2025-10-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_profile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
