# Generated by Django 5.0.1 on 2025-12-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('cook', 'Cook'), ('helper', 'Helper'), ('allrounder', 'All-rounder'), ('manager', 'Manager'), ('cashier', 'Cashier')], max_length=30, null=True),
        ),
    ]
