# Generated by Django 5.0.1 on 2025-12-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_allowed_pages_user_permissions_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allowed_pages',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
