# Generated by Django 5.0.1 on 2025-10-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(help_text='Recommended: 1280x720 (16:9)', upload_to='featured/')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Featured Image',
                'verbose_name_plural': 'Featured Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
