# Generated by Django 5.0.1 on 2025-12-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_featuredimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredimage',
            name='image',
            field=models.URLField(help_text='Recommended: 1280x720 (16:9)', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_picture',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
