# Generated by Django 5.0.1 on 2025-12-26 12:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_featuredimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Recommended: 1280x720 (16:9)', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
