<<<<<<< HEAD
# Generated by Django 5.0.1 on 2025-10-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('interior', 'Interior'), ('event', 'Event'), ('other', 'Other'), ('feedback', 'Feedback')], default='other', max_length=50),
        ),
    ]
=======
# Generated by Django 5.0.1 on 2025-10-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('interior', 'Interior'), ('event', 'Event'), ('other', 'Other'), ('feedback', 'Feedback')], default='other', max_length=50),
        ),
    ]
>>>>>>> df6fb379555319efdf513182b2e65dbdd28a0164
