<<<<<<< HEAD
# Generated by Django 5.0.1 on 2025-11-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryimage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_glimpses',
            field=models.BooleanField(default=False),
        ),
    ]
=======
# Generated by Django 5.0.1 on 2025-11-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryimage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_glimpses',
            field=models.BooleanField(default=False),
        ),
    ]
>>>>>>> df6fb379555319efdf513182b2e65dbdd28a0164
