# Generated by Django 5.0.1 on 2025-11-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_galleryimage_is_glimpses'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_zorpido_glimpses',
            field=models.BooleanField(default=False),
        ),
    ]
