<<<<<<< HEAD
# Generated by Django 5.0.1 on 2025-10-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(help_text='Short description', max_length=5000),
        ),
    ]
=======
# Generated by Django 5.0.1 on 2025-10-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(help_text='Short description', max_length=5000),
        ),
    ]
>>>>>>> df6fb379555319efdf513182b2e65dbdd28a0164
