# Generated by Django 5.0.1 on 2025-12-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogpost_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
