# Generated by Django 5.0.1 on 2025-11-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_seller_expense_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('qr', 'QR')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='paid', max_length=10),
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payable', to='pos.expense')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='pos.seller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
