# Generated by Django 5.0.1 on 2025-12-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_attendance_shift_attendanceaudit_attendance_shift_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='attendanceaudit',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendanceaudit',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceAudit',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
