# Generated by Django 5.0.1 on 2025-12-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_remove_expense_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
