# Generated by Django 5.0.1 on 2025-12-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_add_expenses'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='pos_expense_date_467b66_idx',
            old_name='pos_expense_date_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='pos_expense_categor_4c54b3_idx',
            old_name='pos_expense_cat_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
