# Generated by Django 5.0.1 on 2025-12-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_fix_missing_expense_columns'),
        ('pos', '0015_fix_missing_expense_columns'),
    ]

    operations = [
    ]
