# Generated by Django 5.0.1 on 2025-10-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'order', 'name'], 'permissions': (('manage_inventory', 'Can manage inventory'),), 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
    ]
