# Generated by Django 5.0.1 on 2025-12-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_ensure_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
